version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: podman/Dockerfile
    command: ["pnpm", "run", "dev"]
    environment:
      NODE_ENV: development
      PORT: "3000"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=ae-framework,service.version=1.0.0
    ports:
      - "3000:3000"
    user: "1001:1001"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
    read_only: false
    volumes:
      - ../:/workspace:Z
      - ae_data:/app/.ae
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:3000/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"
    depends_on:
      - db
      - otel

  db:
    image: docker.io/library/postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 10s
      timeout: 5s
      retries: 5

  otel:
    image: docker.io/otel/opentelemetry-collector:0.106.1
    volumes:
      - ../observability/otel-collector.yaml:/etc/otelcol/config.yaml:ro,Z
    ports:
      - "4317:4317"
      - "4318:4318"
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --no-verbose --spider http://localhost:4318/v1/metrics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ae_data:
  pgdata:
