name: "Setup pnpm via Corepack"
description: "Ensures pnpm@10 is available before using actions/setup-node cache"
author: "ae-framework-maintainers"
inputs:
  version:
    description: "pnpm version to activate"
    default: "10.0.0"
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        set -euo pipefail
        VERSION="${{ inputs.version }}"
        MIN_NPM="10.5.0"
        CURRENT_NPM="$(npm --version 2>/dev/null || true)"
        if [ -z "$CURRENT_NPM" ]; then
          echo "npm not found; installing npm@latest-10"
          npm install -g "npm@latest-10"
        else
          LOWEST="$(printf '%s\n' "$MIN_NPM" "$CURRENT_NPM" | sort -V | head -n1)"
          if [ "$LOWEST" != "$MIN_NPM" ]; then
            echo "Detected npm version $CURRENT_NPM < $MIN_NPM; upgrading to npm@latest-10"
            npm install -g "npm@latest-10"
          fi
        fi
        if command -v corepack >/dev/null 2>&1; then
          corepack enable > /dev/null 2>&1 || true
          corepack prepare "pnpm@${VERSION}" --activate
        else
          npm install -g "pnpm@${VERSION}"
        fi
        pnpm --version
      shell: bash
