name: Adapter Thresholds (Report-Only)

on:
  pull_request:

permissions: read-all

jobs:
  summarize-a11y:
    if: contains(github.event.pull_request.labels.*.name, 'run-adapters')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Summarize a11y results (report-only)
        id: a11y
        run: |
          set -e
          FILE="reports/a11y-results.json"
          if [ ! -f "$FILE" ]; then
            printf "%s\n" "present=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          critical=$(jq -r '.violations.critical // 0' "$FILE" 2>/dev/null || printf "0\n")
          serious=$(jq -r '.violations.serious // 0' "$FILE" 2>/dev/null || printf "0\n")
          moderate=$(jq -r '.violations.moderate // 0' "$FILE" 2>/dev/null || printf "0\n")
          minor=$(jq -r '.violations.minor // 0' "$FILE" 2>/dev/null || printf "0\n")
          passes=$(jq -r '.passes // 0' "$FILE" 2>/dev/null || printf "0\n")
          comps=$(jq -r '.components_tested | length' "$FILE" 2>/dev/null || printf "0\n")
          printf "%s\n" "present=true" >> "$GITHUB_OUTPUT"
          printf "%s\n" "critical=$critical" >> "$GITHUB_OUTPUT"
          printf "%s\n" "serious=$serious" >> "$GITHUB_OUTPUT"
          printf "%s\n" "moderate=$moderate" >> "$GITHUB_OUTPUT"
          printf "%s\n" "minor=$minor" >> "$GITHUB_OUTPUT"
          printf "%s\n" "passes=$passes" >> "$GITHUB_OUTPUT"
          printf "%s\n" "components=$comps" >> "$GITHUB_OUTPUT"
      - name: Comment PR with a11y summary
        if: steps.a11y.outputs.present == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const header = '<!-- AE-ADAPTER-A11Y -->\n';
            const body = [
              header,
              '### Accessibility',
              '',
              `Violations: critical=${{ steps.a11y.outputs.critical }}, serious=${{ steps.a11y.outputs.serious }}, moderate=${{ steps.a11y.outputs.moderate }}, minor=${{ steps.a11y.outputs.minor }}`,
              `Passes: ${{ steps.a11y.outputs.passes }}, Components tested: ${{ steps.a11y.outputs.components }}`,
              '',
              `${{ contains(github.event.pull_request.labels.*.name, 'enforce-a11y') && 'Policy: enforced (label: enforce-a11y)' || 'Policy: report-only' }}`,
              'Docs: docs/quality/adapter-thresholds.md'
            ].join('\n');
            const { owner, repo, number } = context.issue;
            const comments = await github.rest.issues.listComments({ owner, repo, issue_number: number, per_page: 100 });
            const mine = comments.data.find(c => c.body && c.body.startsWith(header));
            if (mine) {
              await github.rest.issues.updateComment({ owner, repo, comment_id: mine.id, body });
            } else {
              await github.rest.issues.createComment({ owner, repo, issue_number: number, body });
            }
      - name: Enforce a11y thresholds (critical/serious==0)
        if: steps.a11y.outputs.present == 'true' && contains(github.event.pull_request.labels.*.name, 'enforce-a11y')
        run: |
          crit=${{ steps.a11y.outputs.critical }}
          seri=${{ steps.a11y.outputs.serious }}
          if [ "$crit" -gt 0 ] || [ "$seri" -gt 0 ]; then
            printf "%s\n" "::error::a11y violations exceed threshold (critical=$crit, serious=$seri)"
            exit 1
          fi
