name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  # Ensure quality gates pass before release
  quality-check:
    name: Quality Check
    uses: ./.github/workflows/quality-gates-centralized.yml
    with:
      environment: production

  # Run fast CI tests
  ci-check:
    name: CI Check  
    uses: ./.github/workflows/ci-fast.yml

  # Main release job - only runs if quality and CI checks pass
  release:
    runs-on: ubuntu-latest
    needs: [quality-check, ci-check]
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22, cache: 'pnpm' }
      - run: corepack enable
      - run: pnpm install --frozen-lockfile || pnpm install --no-frozen-lockfile
      - run: pnpm run build

      - name: Bin smoke check
        run: node scripts/ci/check-bins.mjs
      
      - name: Generate SBOM
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b . v1.0.0
          ./syft packages dir:. -o cyclonedx-json > sbom.json
      
      - name: Build Docker image
        run: |
          docker build -t ${{ github.repository }}:${{ github.ref_name }} .
      
      - name: Sign with Sigstore
        run: |
          # Placeholder for Sigstore signing
          printf "%s\n" "Signing artifacts with Sigstore..."
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sbom.json
            security/sigstore/*
          generate_release_notes: true
      
      - name: Deploy Canary
        run: |
          printf "%s\n" "Deploying canary version..."
          # Placeholder for canary deployment
