name: Workflow Lint
on:
  pull_request:
  push:
    branches: [main, develop]
permissions: read-all
jobs:
  actionlint:
    runs-on: ubuntu-latest
    continue-on-error: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ci-non-blocking') }}
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/actionlint@v1.7.1
      - name: Check for unresolved merge markers in workflows
        run: |
          set -e
          if grep -R -nE '<<<<<<<|>>>>>>>|=======' .github/workflows; then
            printf "%s\n" "Unresolved merge markers found in workflows" >&2
            exit 1
          fi
