name: Workflow Lint
on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'scripts/ci/**'
  push:
    branches: [main, develop]
    paths:
      - '.github/workflows/**'
      - 'scripts/ci/**'
permissions: read-all
jobs:
  actionlint:
    runs-on: ubuntu-latest
    continue-on-error: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'ci-non-blocking') }}
    steps:
      - uses: actions/checkout@v4
      - name: Enforce printf policy for outputs/env
        run: bash scripts/ci/guard-github-outputs.sh
      - name: Guard self-test (offender/ok cases)
        run: bash scripts/ci/tests/test-guard.sh
      - name: Suggest echo->printf conversions (non-blocking)
        run: pnpm -s ci:guard:suggest || true
      - uses: rhysd/actionlint@v1.7.1
      - name: Check for unresolved merge markers in workflows
        run: |
          set -e
          if rg -n "<<<<<<<|>>>>>>>|=======" .github/workflows -S || true; then
            printf "%s\n" "Unresolved merge markers found in workflows" >&2
            exit 1
          fi
